### ISSUE TITLE
Termux support 

### ISSUE THREAD

**Issue by empty8005** [hidden-r4d/Rust-Raid-Toolbox#1]
It not bug to , but original raid tool supports termux as I read in repo I never used this raid toll box but I wanted to use it on my server .
Will u going to add termux also or not just asking not forcing to u to made version for termux

**Comment by hidden-r4d** [comment]
Why do you need termux support for it to run on your server? What operating system does your server use that Windows or Linux support will not help?

**Comment by empty8005** [comment]
Sadly I don't have server
